### ISSUE TITLE
View Configuration is broken with recent file-based changes

### ISSUE THREAD

**Issue by deco521** [Cacti/plugin_routerconfigs#69]
Hi. It looks like the Current config view is looking at the config stored in the plugin_routerconfigs_backups table for display, not the file, so removing config/$data2 from the INSERT statement (Issue 64 - functions.php) breaks that functionality. Changing the insert back to the prvious version (ie including config) resolves the issue. It could probably also be fixed by having the Current config view look at the file instead of the database field. Thanks.

**Comment by netniV** [comment]
Hmm, that's not good, I'll take a look now and fix it up.

**Comment by netniV** [comment]
@deco521 what version are you running? The version of router-compare.php that I am looking at uses the directory and filename not data to do the compare.

**Comment by deco521** [comment]
Hi Mark. Sorry, I should have been clearer. router-compare works awesome now with the changes. The problem I'm seeing is in view_device_config() in router-devices.php. That's just pulling the config from the database and displaying it in a textarea. (Line 251 - print $device['config'];). Thanks.

**Comment by netniV** [comment]
Ah, OK, I'll have the fixed shortly then. 👍

**Comment by netniV** [comment]
This should now be resolved.  Let me know if you have any issues.  I haven't got the plugin currently running to be able to fully test but the code looks right.

**Comment by deco521** [comment]
That almost worked. . . It kept giving the missing file message. Here are the four changes I made to get it working.

Line 230: 		$device = db_fetch_row_prepared('SELECT prb.*, prd.hostname, prd.ipaddress
(removed "prd.directory" so it would use the directory in plugin_routerconfigs_backups like it should, instead of the one in plugin_routerconfigs_devices)

Line 242: 		$lines = @file($filepath);
(removed "FILE_IGNORE_NEW_LINES" - config is displayed in textarea, so we need newlines)

Line 260:		print '</h1><textarea rows=36 cols=120 style="height:auto;background:#ffffff;">';
(added "style=..." to override css that causes the textarea to be only a couple of lines long, so 36 rows show up as expected)

Line 261:		print implode($lines);
( \n isn't needed, because config is displaying in textarea, which just displays it as "\n" on every line, instead of as a newline)

Also, I noticed that there's a view_device_config() in router-backups.php that's also looking for the database entry instead of the file.

Thanks!

**Comment by netniV** [comment]
It should really be a common function then.  If you can generate a diff file I will apply it and push the update through.

**Comment by deco521** [comment]
Will do. Thanks.

**Comment by deco521** [comment]
Took a look and the view_device_config() functions in router-devices.php and router-backups.php are a bit different. One displays the most recent config, and one displays a specific config, so I didn't make a common function. Here's the diff for the two files separately.

Thanks.

[20180504-deco521-issue69.zip](https://github.com/Cacti/plugin_routerconfigs/files/1975328/20180504-deco521-issue69.zip)

**Comment by netniV** [comment]
Well, the common function would just take a backup id and return the configuration 👍 

But, I can take your diff and work my magic on it. Thanks.

**Comment by deco521** [comment]
Thanks! If the last backup id was stored in the devices table with the last backup date, then it would be trivial ;) As it is, in one case you have the backup id, in the other you need to figure it out based on the most recent btime for a device. I do get what you're saying, though.

**Comment by netniV** [comment]
I'll just make it so that if an id isn't passed it'll be -1, then it'll look up the latest backup automatically.

**Comment by netniV** [comment]
Just pushed through some more updates.  I haven't had time to test the functionality but I looked over it a few times and it looks right.

**Comment by deco521** [comment]
It's not working quite right for me with these changes. From router-devices.php where it's passing the device id, it's displaying the oldest config available for the device, instead of the newest/current. For router-backups.php where it's passing the backup id, I'm getting Error: 500 Internal Server Error
Reason: The response to the last action was unexpected.

**Comment by netniV** [comment]
Can you check your apache error log and see what error is being recorded?  I'll fix the device-id query now.

**Comment by deco521** [comment]
Here are the relevant Apache error log entries. . .
[Sun May 06 09:41:43.596996 2018] [:error] [pid 59364] [client 172.18.77.89:58862] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /usr/share/cacti/site/lib/html_utility.php on line 286, referer: http://is18/cacti/plugins/routerconfigs/router-backups.php?device=7
[Sun May 06 09:41:43.597102 2018] [:error] [pid 59364] [client 172.18.77.89:58862] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0, referer: http://is18/cacti/plugins/routerconfigs/router-backups.php?device=7
[Sun May 06 09:41:43.597156 2018] [:error] [pid 59364] [client 172.18.77.89:58862] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0, referer: http://is18/cacti/plugins/routerconfigs/router-backups.php?device=7

**Comment by netniV** [comment]
That claims to be out of memory which is an issue that should have occurred before.  Have you ever noticed that before?

**Comment by netniV** [comment]
I've pushed two changes up, see if they work for you.

**Comment by deco521** [comment]
Nope. Never had an out of memory error before the last update. My setting is for PHP scripts not to use more than 128MB. . .

apache2/php.ini: 
memory_limit = 128M

I'm still seeing that get bumped at html_utility.php on line 286

**Comment by netniV** [comment]
I've bumped it in the latest changes yesterday to go up to 256MB. That should be OK since it was used in the rest of the code.

**Comment by deco521** [comment]
From router-devices.php, it's now displaying the header information for the correct config (newest/current), but the textarea is blank now - no config displaying. 

For router-backups.php it still crashes at 256MB. I upped the memory limit to a Gig, just to see, and still exhaust that and crash.

**Comment by netniV** [comment]
That sounds like a recursion issue going on.  I'll take a look and see what I can see.

**Comment by netniV** [comment]
OK, finally had a chance to test this and correct a couple of minor mistakes. Please test it, and if it's OK you can close this issue.

**Comment by deco521** [comment]
Looks great! Thanks for all your work,
